risky: false
version: 8.0
preset: recommended
tab-width: 4
use-tabs: false
enabled:
  - unalign_double_arrow
disabled:
  - align_double_arrow
finder:
  exclude:
    - "tests"
  name:
    - "*.php"
  depth:
    - "< 3"